from app.models import db, Measurement


def seed_measurements():
    a = Measurement(name='tsp.')
    b = Measurement(name='Tbsp.')
    c = Measurement(name='cup')
    d = Measurement(name='fl oz.')
    e = Measurement(name='pint')
    f = Measurement(name='cups')
    g = Measurement(name='pints')
    h = Measurement(name='quart')
    i = Measurement(name='quarts')
    j = Measurement(name='gallon')
    k = Measurement(name='gallons')
    l = Measurement(name='lb')
    m = Measurement(name='lbs')
    n = Measurement(name='ml')
    o = Measurement(name='oz')
    p = Measurement(name='g')
    q = Measurement(name='kg')
    r = Measurement(name='drop')
    s = Measurement(name='drops')

    db.session.add(a)
    db.session.add(b)
    db.session.add(c)
    db.session.add(d)
    db.session.add(e)
    db.session.add(f)
    db.session.add(g)
    db.session.add(h)
    db.session.add(i)
    db.session.add(j)
    db.session.add(k)
    db.session.add(l)
    db.session.add(m)
    db.session.add(n)
    db.session.add(o)
    db.session.add(p)
    db.session.add(q)
    db.session.add(r)
    db.session.add(s)

    db.session.commit()


def undo_measurements():
    db.session.execute('TRUNCATE measurements RESTART IDENTITY CASCADE;')
    db.session.commit()
