"""empty message

Revision ID: 12639bf38a12
Revises: 5dbeab76f2f2
Create Date: 2021-06-30 12:52:26.010768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12639bf38a12'
down_revision = '5dbeab76f2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('plan_category', sa.String(), nullable=True))
    op.drop_column('recipes', 'planCategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('planCategory', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'plan_category')
    # ### end Alembic commands ###
